- cards/src/main/resources/cards/custom/group3/bug/classic/spell_teamwork.json
- cards/src/main/resources/cards/custom/group3/bug/kobolds_and_catacombs/weapon_maexxnas_femur.json
- cards/src/main/resources/cards/custom/group3/bug/the_old_gods/spell_elementium_shell.json
- cards/src/main/resources/cards/custom/group3/bug/the_old_gods/spell_swarm_shield.json
Teamwork -> 7 mana
Elementium Shell -> 3 mana, no draw, only buffs health
Maexnna's Femur -> 8 mana, 2 durability
Swarm Shield -> 2 mana, 3 armor gained
> Bug Balance Changes

- cards/src/main/resources/cards/custom/barongroup/minion_fellow_academite.json
- cards/src/main/resources/cards/custom/barongroup/minion_general_lauren.json
- cards/src/main/resources/cards/custom/barongroup/minion_gravtisk_the_ancient.json
- cards/src/main/resources/cards/custom/barongroup/minion_lonely_whelpling.json
- cards/src/main/resources/cards/custom/barongroup/minion_lost_legionnaire.json
- cards/src/main/resources/cards/custom/barongroup/minion_loyal_landowner.json
- cards/src/main/resources/cards/custom/barongroup/minion_malicious_magpie.json
- cards/src/main/resources/cards/custom/barongroup/minion_sandman.json
- cards/src/main/resources/cards/custom/barongroup/minion_scurvy_assassin.json
- cards/src/main/resources/cards/custom/barongroup/minion_scurvy_swaggler.json
- cards/src/main/resources/cards/custom/barongroup/minion_the_jekka_tree.json
- cards/src/main/resources/cards/custom/barongroup/spell_conjured_drifts.json
- cards/src/main/resources/cards/custom/barongroup/spell_midsummer_mirage.json
- cards/src/main/resources/cards/custom/barongroup/spell_veiled_protection.json
- cards/src/main/resources/cards/custom/barongroup/spell_weak_point.json
- cards/src/main/resources/cards/custom/barongroup/token_gale.json
- cards/src/main/resources/cards/custom/minion_cyclotron.json
> Barons Verdant Dreams Cards

- cards/src/main/resources/cards/custom/group6/witch_doctor/Verdant Dreams/spell_recurring_nightmare.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_avatar_of_hakkar.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_birdbrain.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_blood_transfuser.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_darkwill_appraiser.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_doctosaur.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_dreadweaver.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_mind_controlled_mech.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_packmother.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_raptor_rider_raider.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_spirited_bomber.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_vilewing_broodmother.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_winterfang_seer.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_zalmah.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_abduction.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_bone_bond.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_cursed_mirror.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_cycle_of_undeath.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_drain_sanity.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_kanov_worms.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_mass_production.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_rage_ascension.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_spiritball.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_stolen_scarabs.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/token_spiritfused_machine.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/token_voodoo_scarab.json
I did not touch the card file names themselves. I simply changed in the card itself. I added comments to what I did for each one.
> Updated Witch Doctor cards + Minor Reflavoring.

- cards/src/main/resources/cards/custom/group0/doombubbles/neutral/minion_aegwynn.json
- cards/src/main/resources/cards/custom/group0/doombubbles/neutral/minion_dragonling_pet.json
- cards/src/main/resources/cards/custom/group0/doombubbles/neutral/minion_hatches_the_dragon.json
- cards/src/main/resources/cards/custom/group0/the_sands_of_time/neutral/permanent_the_end_time.json
Sees play in combination with Hatches in too many decks. Auto-include.
> Rework overpowered cards (code might be wrong idk)

- game/src/main/java/net/demilich/metastone/game/spells/custom/SummonMinionWithMostCopiesInDeckSpell.java
- www/whatsnew.md
- www/windowsdevelopment.md
Changes Yig's Mastermind mana cost from 8 to 10
> Muhframos patch 1

- cards/src/main/resources/cards/custom/group3/set_1087/minion_fireguard_bulwark.json
- www/whatsnew.md
> Fixes bug where Fireguard Bulwark didn't have guard

- cards/src/main/resources/cards/custom/group2/summoner/minion_energetic_mentee.json
- www/whatsnew.md
> Specifies that Energetic Mentee's first ability is an opener

- cards/src/main/resources/cards/custom/group8/occultist/ungoro/minion_distortoise.json
- www/whatsnew.md
> Distortoise now correctly does 3 damage to the owner

- cards/src/main/resources/cards/custom/group6/witch_doctor/minion_prized_boar.json
- www/whatsnew.md
> Fixes Prized Boar aftermath effect

- cards/src/main/resources/cards/custom/group8/occultist/witchwood/minion_monolith_of_doom.json
- game/src/test/java/com/hiddenswitch/spellsource/CustomCardsTests.java
- www/whatsnew.md
> Fixes Monolith of Doom Description and tests

- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/minion_blight_harvester.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/minion_blighted_ent.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/minion_fae_embalmer.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/minion_fae_wraith_caroline.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/minion_large_spiderling.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/minion_zathahun_bloodthirsty.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/pact_binding_nightmare.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/spell_ancient_curse.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/spell_auto_cannibalism.json
- cards/src/main/resources/cards/custom/group4/wraith/Verdant Dreams/spell_blight_hosts.json
- cards/src/main/resources/cards/custom/group4/wraith/spell_drain.json
- cards/src/main/resources/cards/custom/group4/wraith/token_skeleton2guard_wraith.json
think this is what I did last time
> Wraith VD cards

- cards/src/main/resources/cards/custom/group8/occultist/basic/spell_ancient_blood.json
- cards/src/main/resources/cards/custom/group8/occultist/classic/spell_bloodmoon_ritual
- cards/src/main/resources/cards/custom/group8/occultist/misc/minion_azathoth
- cards/src/main/resources/cards/custom/group8/occultist/misc/minion_bloodthirsty_maneater
- cards/src/main/resources/cards/custom/group8/occultist/misc/minion_gobogeg
- cards/src/main/resources/cards/custom/group8/occultist/misc/minion_spawn_of_gobogeg
- cards/src/main/resources/cards/custom/group8/occultist/misc/minion_twisted_flesh
- cards/src/main/resources/cards/custom/group8/occultist/misc/spell_cosmic_apparitions
- cards/src/main/resources/cards/custom/group8/occultist/misc/spell_grasp_of_god
- cards/src/main/resources/cards/custom/group8/occultist/misc/spell_necronomicon
- cards/src/main/resources/cards/custom/group8/occultist/misc/spell_revelation
- cards/src/main/resources/cards/custom/group8/occultist/misc/spell_unholy_tremors
- cards/src/main/resources/cards/custom/group8/occultist/misc2/minion_astral_anomaly.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/minion_decaying_colossus.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/minion_shaklatal_cosmos_scion.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/minion_star_sculptor.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/minion_the_rotten.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/spell_celestial_imprisonment.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/spell_cosmos_rift.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/spell_foul_manifest.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/spell_goreball.json
- cards/src/main/resources/cards/custom/group8/occultist/misc2/spell_otherwordly_truth.json
- cards/src/main/resources/cards/custom/group8/occultist/ungoro/minion_distortoise.json
Doc idk why these old commits are in this pull request but pls dont put anything from before december 4th in this pull request into the game just so nothing bad gets changed (which might).
> New Occultist Set also help

- cards/src/main/resources/cards/custom/group10/spellsource_core_common/minion_dragonfruit_whelp.json
- cards/src/main/resources/cards/custom/group10/spellsource_core_common/minion_natural_convert.json
- cards/src/main/resources/cards/custom/group10/spellsource_core_common/minion_soup_savant.json
- cards/src/main/resources/cards/custom/group8/basic_core/minion_divine_cleric.json
> Neutral healing rebalances

- cards/src/main/resources/cards/custom/group8/occultist/misc/minion_gobogeg
- cards/src/main/resources/cards/custom/group8/occultist/misc3/minion_council_of_fate.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/minion_crazed_cultlord.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/minion_cyaegha_the_curious.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/minion_herald_of_fate.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/minion_sunken_terror.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_arduous_invocation.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_curse_of_desolation.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_fated_sabotage.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_forgotten_grimoire.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_mind_tear.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_renew_it.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_reshape_it.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_restore_it.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_ruin_it.json
- cards/src/main/resources/cards/custom/group8/occultist/misc3/spell_substitute.json
- cards/src/main/resources/cards/custom/group8/occultist/wotog/minion_chaugnar_the_corruptor.json
- cards/src/main/resources/cards/custom/group8/occultist/wotog/spell_evil_rises.json
Two card fixes, a card rework, and an entire new set with 10 new cards!
Please code peeps look at my cards so they work properly when they get in the game aaa
> Occultist Changes

- cards/src/main/resources/cards/custom/group4/wraith/basic/spell_back_for_more.json
> minor overlord nerf

- cards/src/main/resources/cards/custom/storyteller/classic/minion_piglet_knight.json
Originally was supposed to have Beast tag, more reason to now due to Fae Flyrider
> Giving Piglet Knight Beast Tag

- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/hero_power_diamond_sultan.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_aeon_channeler.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_greedy_adventurer.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_inept_investigator.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_monumancer.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_senior_explorer.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_the_diamond_sultan.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_vitium_surger.json
- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/spell_the_cyntanami.json
Adding a few new cards as a follow-up to the previous pull request. What Lies Beneath as an expansion will see some significant changes in the future and I most likely won't be coding the rest of its cards just yet, but I figured I should get the generator cards for the Artifacts I added into the game so that people can play around with Artifacts while they last.
> What Lies Beneath - Artifact Gen

- cards/src/main/resources/cards/custom/Dipsy/What_Lies_Beneath/artifact_generators/minion_vitium_surger.json
- cards/src/main/resources/cards/custom/arch/what_lies_beyond/spell_gold_rush.json
- cards/src/main/resources/cards/custom/group8/occultist/occultist changes 2/spell_rite_of_worship.json
- cards/src/main/resources/cards/custom/group8/occultist/what_lies_beneath/minion_knowledge_hoarder.json
- cards/src/main/resources/cards/custom/group8/occultist/what_lies_beneath/minion_primordial_miner.json
- cards/src/test/java/com/hiddenswitch/spellsource/tests/cards/ArchaeologistTests.java
- cards/src/test/java/com/hiddenswitch/spellsource/tests/cards/CustomCardsTests.java
- cards/src/test/java/com/hiddenswitch/spellsource/tests/cards/OccultistTests.java
- game/src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- game/src/main/java/net/demilich/metastone/game/spells/DrawCardFromGraveyardSpell.java
- game/src/main/java/net/demilich/metastone/game/spells/custom/CelestialConduitSpell.java
- www/src/pages-markdown/whatsnew.md
Fix #1683
Fix #1684
Fix #1685
Fix #1686
Fix #1688
Fix #1689
Fix #1690
> Apr 8 fixes

- cards/src/main/resources/cards/custom/Skyward/basic/minion_high_flier.json
- cards/src/main/resources/cards/custom/Skyward/core/minion_esoteric_aeronaut.json
- cards/src/main/resources/cards/custom/Skyward/core/spell_skyfall.json
- cards/src/main/resources/cards/custom/Skyward/setless/sourcestorm/minion_thunderclap_phoenix.json
- cards/src/main/resources/cards/custom/Skyward/setless/verdant dreams/spell_dream_of_ascendance.json
- cards/src/main/resources/cards/custom/Skyward/zdeleted/token_firebolt.json
Skyfall cost -> 9
Thunderclap Phoenix cost -> 8
Dream of Ascendance costs 10 and Firebolts only deal 2 damage.
Esoteric Aeronaut is 0/3 instead of 1/1.
High Flier cost to 6, but targets all spells.
> Some Skyward balance updates.

- cards/src/main/resources/cards/custom/group10/spellsource_core_legendary/minion_doodles_v2.json
- cards/src/main/resources/cards/custom/group6/witch_doctor/spell_bat-talion.json
Quick fixes
- Fix bat-talion plural 
- Update doodles v2 description
Closes #1754 
Closes #1755
> Update some card descriptions
